# Dolthub_vols: dolthub volatility data, generated by me 

# Dolthub option data
{
    # Only January 2024
    dolthub_2024 <- read_csv("/home/marco/trading/HistoricalData/Dolthub/sample_2024.csv") %>% 
        rename(Date=date, Symbol=act_symbol, IV=vol) %>% 
        mutate(Date=as.Date(Date), expiration=as.Date(expiration), dte = expiration-Date) #%>% filter(call_put=="Put" & abs(round_to_nearest(delta, 0.05)) == 0.5)
    dolthub_2024 <- inner_join(dolthub_2024, stock_price_data, by=c("Symbol", "Date"))
    dolthub_2024 <- inner_join(dolthub_2024, Stocks_Info, by=c("Symbol"))
    dolthub_2024 <- dolthub_2024 %>% mutate(
        VRP = IV - RV,
        VRPlog = log(IV / RV),
        VRPadj = VRPlog / HV1,
        VRPvega = vega * (IV - RV)
    )
    
    # Generate volatility data from dolthub options data 
    # (I want to know if I can recreate volatility summary similar to barchart data like https://www.barchart.com/stocks/quotes/AAPL/options-history)
    # I select option close to 0.5 delta, and weight all contracts according to distance from expiration
    {
        dir <- "/home/marco/trading/HistoricalData/Dolthub/Split_by_stock/"
        files <- list.files(dir, pattern = "*.csv")
        Dolthub_vols_list <- list()
        for(f in files){
            n <- sub("sample_", "", f) %>% sub(".csv", "", .)
            if(!n %in% names(Price_data_stocks))
                next
            print(n)
            # Load the file and calculate dte and distance from 30 days
            df_file <- fread(paste0(dir, f)) %>% rename(Date=date) %>% 
                mutate(Date=as.Date(Date), expiration=as.Date(expiration), dte = as.numeric(expiration-Date), vol = case_when(vol == -1 ~ NA, TRUE ~ vol)) %>% 
                mutate(delta_ = abs(round_to_nearest(delta, 0.1)), dist = 1/(abs(dte - 30)+1))
            # Extract ATM options and calculate weights
            df_w <- df_file %>% group_by(Date) %>%  filter(delta_==0.5) %>% 
                group_by(Date, expiration) %>% reframe(M=mean(vol), dist=first(dist), vega=first(vega), bid=first(bid), ask=first(ask))  %>% 
                group_by(Date) %>% mutate(W = (dist / sum(dist))) 
            # ATm weighted means and term structure slopes
            df_iv <- group_by(df_w, Date) %>% reframe(IV = sum(M*W, na.rm=T), Slope = log(last(M)/first(M)), vega=first(vega), bid=first(bid), ask=first(ask))
            # Volatility smile skew
            df_skew <- df_file %>% filter(delta_ < 0.50) %>% group_by(Date, expiration, call_put) %>% reframe(M=mean(vol), dist=first(dist)) %>% # average of calls and puts by contract and date
                group_by(Date) %>% mutate (W = dist / sum(dist)) %>% # normalize dte distance
                group_by(Date, expiration) %>% reframe(S = log(last(M) / first(M)), W=first(W)) %>% # expirations skews
                group_by(Date) %>% reframe(Skew = sum(S*W)) # weighed average of expirations skews
            df <- inner_join(df_iv, df_skew, by="Date") %>% arrange(Date)
            df <- inner_join(df, Price_data_stocks[[n]], by="Date") %>% 
                mutate(IV = case_when(IV == 0 ~ NA, TRUE ~ IV), 
                       VRP = IV - RV,  VRPlog = log(IV / RV),   VRPadj = VRPlog / HV1, VRPvega = vega * VRP) %>% arrange(Date)
            
            # Ignore small files (less than 100 observations)
            if(nrow(df) < 50) 
                next
            Dolthub_vols_list[[n]] <- df
        }
        
        Dolthub_vols_chains <- do.call(rbind, Dolthub_vols_list) %>% inner_join(., Stocks_Info, keep=FALSE, by="Symbol")
        write_csv(Dolthub_vols_chains, "/home/marco/trading/HistoricalData/Barchart/Options/Dolthub_vols_chains.csv")
    }
    
    
    # Generate ATM straddles (you need the lists Price_data_stocks and Stocks_Info, see above)
    # PROBABLY INCORRECT AS DOLTHUB DATA PRESENTS HOLES
    {
        Straddles <- list()
        dir <- "/home/marco/trading/HistoricalData/Dolthub/Split_by_stock//"
        for(f in list.files(dir, pattern = "*.csv")){
            df <- fread(paste0(dir, f)) %>% as.data.frame() %>% rename(Date=date, Symbol=act_symbol) %>% 
                mutate(Date=as.Date(Date), expiration=as.Date(expiration), dte = expiration-Date)
            symbol <- as.character(head(df$Symbol, 1))
            print(symbol)
            if(symbol %in% names(Straddles)) next
            prices <- Price_data_stocks[[symbol]]
            if(is.null(prices) || nrow(Price_data_stocks[[symbol]]) < 500 | !symbol %in% Stocks_Info$Symbol) next
            df <- inner_join(df, prices, by=c("Date", "Symbol")) 
            if(nrow(df) == 0) next
            stdls <- df %>% 
                mutate(diff = abs(Close - strike)) %>% # I think Close is more correct than AdjClose (we are before dividends split)
                group_by(Symbol, Date, expiration, call_put) %>% mutate(m=min(diff), ATM=m==diff) %>% 
                group_by(Symbol, Date, expiration, strike) %>% reframe(straddle = sum(ask), spread=sum(ask-bid)/2, IV = sum(vol), delta=sum(delta), gamma=sum(gamma), theta=sum(theta), vega=sum(vega), rho=sum(rho), dte=first(dte), ATM=first(ATM), Close=first(Close)) %>% 
                mutate(ID=paste(Symbol, expiration, strike, sep="_")) %>% arrange(Date) %>% 
                group_by(ID) %>% mutate(Return=log(lead(straddle)/straddle), Cost=spread/straddle+lead(spread)/lead(straddle)) %>% # Here Return is the future return, in case you are entering the position now
                filter(ATM==TRUE)
            stdls <- cbind(stdls, Stocks_Info %>% filter(Symbol == symbol) %>% dplyr::select(-Symbol)) 
            stdls <- inner_join(stdls %>% dplyr::select(-Close), Price_data_stocks[[symbol]], by=c("Symbol", "Date")) %>% mutate(VRP = IV - RV, VRPlog = log(IV / RV))  %>% filter(!is.infinite(VRPlog)) %>% arrange(Date) 
            Straddles[[symbol]] <- stdls
        }
        straddles <- do.call(rbind, Straddles)
        # Plots
        straddles %>% group_by(Symbol) %>% reframe(VRP=median(VRPlog, na.rm=T), Class=first(`Sector`)) %>% ggplot(aes(y=VRP, x=Class, group=Class)) + geom_boxplot() + geom_hline(yintercept = 0)+ theme(axis.text.x = element_text(angle = 45))
        straddles %>% filter(!is.infinite(Return)) %>% mutate(dte=round(dte/10)) %>% group_by(Symbol, dte) %>% reframe(Ms=median(VRPlog, na.rm=T)) %>% group_by(dte) %>% reframe(M=mean(Ms, na.rm=T), S=sd(Ms, na.rm=T)/sqrt(n()*2), N=n()) %>% filter(N>100) %>% ggplot(aes(x=dte, ymin=M-S, ymax=M+S)) + geom_errorbar(width=0.5) + geom_hline(yintercept = 0)    
    }
    
}

# Dolthub volatility data single file (BEWARE, only 3 days per week, VRPlog might not be calculated)
{
    Dolthub_vols <- read_csv("/home/marco/trading/HistoricalData/Dolthub/post-no-preference_options_master_volatility_history.csv.gz")
    Dolthub_vols <- Dolthub_vols %>% rename(Symbol=act_symbol, Date=date) %>% group_by(Symbol) %>% 
        mutate(rv_current = lead(hv_current, 13), VRPlog = log(iv_current / rv_current)) %>% ungroup # only mon, wed, fri are present, so 13 
    Dolthub_vols <- full_join(Dolthub_vols, Stocks_Info, by="Symbol") %>% ungroup() %>% filter(!is.na(Name) & !is.na(Date))
    Dolthub_vols <- full_join(Dolthub_vols, stock_price_data, by=c("Symbol", "Date")) 
    write_csv(Dolthub_vols, "/home/marco/trading/HistoricalData/Barchart/Options/Dolthub_vols.csv")

    
}

# Dolthub single stock playing with  (SPY as example)
{
    ticker <- "SPY"
    data_opt <- read_csv(paste0("/home/marco/trading/HistoricalData/Dolthub/Split_by_stock//sample_", ticker, ".csv"), show_col_types = F) %>% mutate(mid = (bid+ask)/2, cost = (ask-bid)/ask, id = paste(act_symbol, expiration, strike, call_put, sep="_"), wday = lubridate::wday(date, label=T), dte = as.integer(expiration-date))
    vol_shift <- 21
    data_price <- read_csv(paste0("/home/marco/trading/HistoricalData/Barchart/Options/YahooPrice/Stocks/", ticker, ".csv"), show_col_types = F) %>% 
        rename(date=Date, AdjClose = `Adj Close`) %>% 
        mutate(ReturnPrice = log(AdjClose / lag(AdjClose)),                                                                                                                                                          
               ReturnPrice = replace_na(ReturnPrice, 0),
               Return1week = log(AdjClose / lag(AdjClose, 5)),
               Return6month = log(AdjClose / lag(AdjClose, 120)),
               HV1 = runSD(ReturnPrice, vol_shift) * sqrt(252), 
               HV2 = calculate_volatility(ReturnPrice, long_span = 252, short_span = vol_shift, period = 252),
               RV = lead(HV1, vol_shift))    
    data <- merge(data_opt, data_price, by="date") 
    data <- data %>% mutate(VRP = vol - RV, VRPlog = log(vol / RV), VRPprofit = 1/vega * (vol - RV), VRPprofit_ = (1/vega)/(RV*(365/dte)) * (vol^2 - RV^2))
    # IV vs RV
    data %>% na.omit%>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>% group_by(decile1 = date, decile2=round(delta_, 1)) %>% reframe(RV=first(RV), IV=mean(vol)) %>% ggplot(aes(x=decile1)) + geom_line(aes(y=RV), color="red")+ geom_line(aes(y=IV), color="blue") + facet_wrap(~decile2, scales = "free")
    # VRP (vega weighted)
    data %>% na.omit %>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>% 
        group_by(decile = round(delta_, 1), call_put) %>% reframe(Mean=median(VRPprofit), SD=sd(VRPprofit)/sqrt(n())) %>% ggplot(aes(x=decile, y=Mean, ymin=Mean-SD*2, ymax=Mean+SD*2, color=call_put)) + geom_line() + geom_errorbar(width=0.025)
    data %>% na.omit %>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>% 
        group_by(decile1 = round(delta_, 1), decile2 = round(dte / 10), call_put) %>% reframe(Mean=median(VRPprofit), SD=mad(VRPprofit)/sqrt(n())*2) %>% ggplot(aes(x=decile1, y=Mean, ymin=Mean-SD*2, ymax=Mean+SD*2, color=call_put)) + geom_line() + geom_errorbar(width=0.025)+ facet_wrap(~decile2)  
    # Volatility smile
    data %>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>% group_by(decile = round(delta_, 1), call_put) %>% reframe(Mean=median(vol), SD=sd(vol)/sqrt(n())) %>% ggplot(aes(x=decile, y=Mean, ymin=Mean-SD*2, ymax=Mean+SD*2, color=call_put)) + geom_line() + geom_errorbar(width=0.025)    
    data %>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>% group_by(decile1 = round(delta_, 1), decile2 = round(dte / 10), call_put) %>% reframe(Mean=median(vol), SD=sd(vol)/sqrt(n())) %>% ggplot(aes(x=decile1, y=Mean, ymin=Mean-SD*2, ymax=Mean+SD*2, color=call_put)) + geom_line() + geom_errorbar(width=0.025) + facet_wrap(~decile2)   
    # Weekend effect?
    data_we <- mutate(data, yw = yearweek(date, week_start=1))
    data_we %>% filter(call_put=="Call") %>% group_by(id, yw)  %>% 
        reframe(Time=-c(NA, diff(dte)), Diff=c(NA, diff(mid))/lag(mid)*100, Day=wday, delta=round(delta, 1)) %>% na.omit %>% filter(Diff!=0) %>% group_by(Time) %>% reframe(Mean=median(Diff), SD=mad(Diff)/sqrt(n()), N=n()) 
    # Weekend effect with straddles
    {
        a <- data_opt %>% mutate(delta_ = case_when(call_put=="Call" ~ abs(delta), TRUE ~ 1-delta)) %>%  mutate(delta_ = abs(round_to_nearest(delta, 0.05))) %>% filter(call_put=="Call") %>% select(date, expiration, strike, mid, delta_, vega) 
        b <- data_opt %>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>%  mutate(delta_ = abs(round_to_nearest(delta, 0.05))) %>% filter(call_put=="Put") %>% select(date, expiration, strike, mid, delta_, vega) 
        straddles <- full_join(a, b, by=c("date", "expiration", "strike")) %>% mutate(straddle=mid.x+mid.y, wday=lubridate::wday(date, label=TRUE), id=paste(expiration,strike,sep="_"))
        straddles <- straddles %>% mutate(dte=as.integer(expiration-date)) %>%  group_by(id) %>% mutate(vega=(vega.x+vega.y)/2, profit=c(NA, diff(straddle))/vega)  # profit in dollar terms
        straddles %>% filter(delta_.x==0.5, delta_.y==0.5 & profit != 0) %>% group_by(wday) %>% na.omit %>% reframe(M=mean(profit), sd=sd(profit)/sqrt(n())*2, n=n()) %>% filter(wday %in% c("Mon","Wed","Fri")) 
        }
    # VRP by dte (not totally correct, as the RV should be calculated over the dte)
    data %>% group_by(dte) %>% reframe(M=median(VRPlog, na.rm=T), S=mad(VRPlog, na.rm=T)/sqrt(n()), N=n()) %>% arrange(dte) %>% filter(N>1000) %>% ggplot(aes(x=dte, y=M, ymin=M-S*2, ymax=M+S*2)) + geom_line(color="blue") + geom_errorbar(color="darkgray") + geom_point()
}
