{
    library(derivmkts)
    library(tidyverse)
    library(zoo)
    library(TTR)
    library(data.table)
    library(lubridate)
    library(Rfast)
    library(tsibble)
    library(ggthemes)
    source("/home/marco/trading/Systems/Common/RiskManagement.R")
    source("/home/marco/trading/Systems/Common/Common.R")
    source("/home/marco/trading/Systems/Common/Indicators.R")
    theme_set(theme_bw(base_size = 24))
}

# FILES:
# Price_data_stocks: yahoo price data with additional return and price volatilities, created with for f in `find . -name "*csv"`; do g=`basename $f | sed 's/.csv//'`;  cat $f | sed 's/^/'$g',/g'  ;done | grep -v Date > stock_price_data.csv
# Barchart_vols_stocks: barchart volatility data, created by joining all the single files
# Dolthub_vols: dolthub volatility data, generated by me 
# ORATS_core: ORATS core, containing single day volatility and straddle data
# Stocks_Info: Fundamental data about stocks from barchart
# ETFs_Info: Fundamental data about ETFs from barchart


# Convenience functions
{
get_decimal_places <- function(x) {
    # Convert the number to a string
    x_str <- as.character(x)
    
    # Split the string at the decimal point
    parts <- strsplit(x_str, "\\.")[[1]]
    
    # If there's no decimal point, there are no decimal places
    if (length(parts) == 1) {
        return(0)
    }
    
    # Otherwise, count the number of digits after the decimal point
    return(nchar(parts[2]))
}    
    
round_to_nearest <- function(x, n=0.05) {
        round(round(x / n) * n, get_decimal_places(n))
    }    
    
calloption <- function(s, k, v, r, tt, d, long) {
    bscall(s, k, v, r, tt, d) * long
}

putoption <- function(s, k, v, r, tt, d, long) {
    bsput(s, k, v, r, tt, d) * long
}
    
putoption <- function(s, k, v, r, tt, d, long) {
    bsput(s, k, v, r, tt, d) * long
}

bullspread <- function(s, k1, k2, v, r, tt, d, long) {
    ( bscall(s, k1, v, r, tt, d) - bscall(s, k2, v, r, tt, d) ) * long
}

straddle <- function(s, k, v, r, tt, d, long) {
    ( bscall(s, k, v, r, tt, d) + bsput(s, k, v, r, tt, d) ) * long
}

strangle <- function(s, k1, k2, v, r, tt, d, long) {
    ( bscall(s, k1, v, r, tt, d) + bsput(s, k2, v, r, tt, d) ) * long
}

butterfly <- function(s, k, k1, k2, v, r, tt, d, long) {
    ( - bscall(s, k, v, r, tt, d) - bscall(s, k, v, r, tt, d) + bscall(s, k1, v, r, tt, d) + bscall(s, k2, v, r, tt, d) ) * long
}

ironbutterfly <- function(s, k, k1, k2, v, r, tt, d, long) {
    ( - bscall(s, k, v, r, tt, d) - bsput(s, k, v, r, tt, d) + bsput(s, k1, v, r, tt, d) + bscall(s, k2, v, r, tt, d) ) * long
}

# Use gbm_vec to simulate a GBM
option_sim_profit <- function(gbm, type="call", premium = NULL, X = 100, tt = 1, v=0.3, r = 0, d = 0, hedging = FALSE) {
    if(!type %in% c("call", "put"))
        stop(paste("Option type can be either call or put, not"), type)
    periods <- nrow(gbm)
    tte <- seq(tt, tt/periods, length.out=periods)
    if(type=="call")
        values <- apply(gbm, 2, function(x) bscall(x, X, v, r, tte, d))
    else if(type=="put")
        values <- apply(gbm, 2, function(x) bsput(x, X, v, r, tte, d))
    if(is.null(premium))
        premium <- values[1,]
    hedges <- rep(0, ncol(gbm))
    if(hedging) {
        if(type=="call")
            deltas <- greeks(bscall(values, X, v, r, tt, d), complete=FALSE, long=FALSE, initcaps=FALSE)["delta",]
        else if(type=="put")
            deltas <- greeks(bsput(values, X, v, r, tt, d), complete=FALSE, long=FALSE, initcaps=FALSE)["delta",]
    }
    values <- values + hedges
    price <- as.vector(tail(gbm, 1))
    value <- as.vector(tail(values, 1))
    if(type=="call")
        payoff <- apply(cbind(price-X, 0), 1, max)
    else if(type=="put")
        payoff <- apply(cbind(X-price, 0), 1, max)
    profit <- payoff - premium
    return(data.frame(price=price, value=value, payoff=payoff, profit=profit, hedge=hedges))
}

}

# Yahoo Load assets prices 
{
    Price_data_stocks <- list()
    #Price_data_ETFs <- list()
    Returns <- list()
    type <- "Stocks/"# Stocks or ETFs
    dir <- paste0(main_dir, "YahooPrice/", type)
    vol_shift <- 21; period <- 252
    for(f in list.files(dir, pattern = "*.csv")){
        symbol <- sub(".csv", "", f)
        df <- fread(paste0(dir, f)) %>% as.data.frame()
        colnames(df)[6] <- c("AdjClose") 
        df <- mutate(df, 
            Date = as.Date(df$Date),
            Symbol = symbol,
            ReturnPrice = log(AdjClose / lag(AdjClose)), 
            ReturnPrice = replace_na(ReturnPrice, 0),
            HV1 = runSD(ReturnPrice, vol_shift) * sqrt(period), 
            HV2 = calculate_volatility(ReturnPrice, long_span = period, short_span = vol_shift, period = period),
            HV3 = runSD(ReturnPrice, period) * sqrt(period), 
            RV = lead(HV1, vol_shift),
            Momentum1 = EMA(ReturnPrice, vol_shift)/runSD(ReturnPrice, vol_shift),
            Momentum2 = RSI(na.locf(AdjClose, na.rm=F), vol_shift, maType=EMA)/50-1
        )
        df <- arrange(df, Date)
        Price_data_stocks[[symbol]] <- df
    }
}

# Yahoo Load single file assets prices  
{
    vol_shift <- 21; period <- 252
    stock_price_data <- read_csv("/home/marco/trading/HistoricalData/Barchart/Options/stock_price_data.csv")
    stock_price_data <- 
                 stock_price_data %>% rename(AdjClose = `Adj Close`) %>% arrange(Date) %>% 
                 group_by(Symbol) %>% 
                 mutate(
                     ReturnPrice = log(AdjClose / lag(AdjClose)), 
                     ReturnPrice = replace_na(ReturnPrice, 0),
                     HV1 = runSD(ReturnPrice, vol_shift) * sqrt(period), 
                     HV2 = calculate_volatility(ReturnPrice, long_span = period, short_span = vol_shift, period = period),
                     RV = lead(HV1, vol_shift),
                     Momentum1 = EMA(ReturnPrice, 21)/runSD(ReturnPrice, 21),
                     Momentum2 = RSI(na.locf(AdjClose, na.rm=F), 21, maType=EMA)/50-1
                    )
    stock_price_data <- arrange(stock_price_data, Date)
}

# Barchart historical volatility data (scrape from pages like https://www.barchart.com/stocks/quotes/AAPL/options-history)
{
    # Load barchart volatility prices, and clean that data
    {
        main_dir <- "/home/marco/trading/HistoricalData/Barchart/Options/"
        type <- "Stocks/" # Stocks or ETFs
        Options_data <- list()
        dir <- paste0(main_dir, "BarchartVolatility/", type)
        for(f in list.files(dir, pattern = "*.csv")){
            symbol <- sub(".csv", "", f)
            df <- fread(paste0(dir, f)) %>% as.data.frame
            df$Date <- as.Date(df$Date)
            # Columns after the 7th randomly appears
            df <- df[,1:9]
            colnames(df) <- c("Date", "ImpVol", "IVChg", "IVRank", "IVPctl", "PCVol", "OptionsVol", "PCOI","TotalOI")
            # Remove percentages symbols and commas
            for(n in c("ImpVol", "IVChg", "IVRank", "IVPctl"))
                df[,n] <- df[,n] %>% unlist %>% gsub("\\%|,", "", .) %>% as.numeric
            df <- arrange(df, Date)
            Options_data[[symbol]] <- df
        }
    }
    
    # Merge barchart options and yahoo prices
    {
        # Load Infos
        dir <- "/home/marco/trading/HistoricalData/Barchart/Options/"
        ETFs_Info <- read_csv(paste0(dir, "ETF_Info.csv"), show_col_types = FALSE)
        Stocks_Info <- read_csv(paste0(dir, "Stock_Info.csv"), show_col_types = FALSE)
        # Merge options data and price data, calculate volatilities, filter bad data
        load_price_data <- function(options_data, price_data, vol_shift = 21, period = 252) {
            a <- lapply(names(options_data), function(n) {
                        #print(n)
                        if(nrow(options_data[[n]]) < period | is.null(price_data[[n]]) ) return(NULL)
                        else {
                        full_join(options_data[[n]], price_data[[n]], by="Date") %>% mutate(Symbol=n, .after=Date) %>% arrange(Date) %>% 
                        rename(IV = ImpVol) %>%        
                        mutate(
                            IV = case_when(IV == 0 ~ NA, TRUE ~ IV),
                            IV = IV / 100,
                            IVChg = IVChg / 100,
                            VRP = IV - RV,
                            VRPlog = log(IV / RV),
                            VRPadj = VRPlog / HV1
                            ) 
                        }
            }
                    )
            return(a)
        }
        # Call this for ETFs
        {
        Barchart_vols_ETFs <- load_price_data(Options_data, Price_data_ETFs)
        names(Barchart_vols_ETFs) <- names(Options_data)
        Barchart_vols_ETFs <- do.call(rbind, Barchart_vols_ETFs) %>% inner_join(., ETFs_Info, keep=FALSE, by="Symbol")
        write_csv(Barchart_vols_ETFs, "/home/marco/trading/HistoricalData/Barchart/Options/Barchart_vols_ETFs.csv")
        }
        # Call this for Stocks
        {
        Barchart_vols_stocks <- load_price_data(Options_data, Price_data_stocks)
        names(Barchart_vols_stocks) <- names(Options_data)
        Barchart_vols_stocks <- do.call(rbind, Barchart_vols_stocks) %>% inner_join(., Stocks_Info, keep=FALSE, by="Symbol")
        write_csv(Barchart_vols_stocks, "/home/marco/trading/HistoricalData/Barchart/Options/Barchart_vols_stocks.csv")
        }
    }
}

# Barchart historical single option data (the ones individually scraped from pages like https://www.barchart.com/stocks/quotes/SPY%7C20200814%7C321.00C/price-history/historical)
{
    dir <- "/home/marco/trading/HistoricalData/Barchart/OTHER/Options/Data/Daily/SPY/" 
    prefix <- "_opt."
    delim <- "%7C"
    files <- list()
    for (f in list.files(dir, pattern = "*csv", full.names = T)) {
        df <- fread(f, sep=",")
        items <- (f %>% basename %>% sub(prefix, "", .) %>% sub(".csv", "", .) %>% strsplit(., delim))[[1]]
        symbol <- items[1]
        expiry <- as.Date(items[2], format="%Y%m%d")
        strike <- as.numeric(substr(items[3], 1, nchar(items[3])-1))
        type <- substr(items[3], nchar(items[3]), nchar(items[3]))
        df <- df %>% mutate(Symbol=symbol, Expiry=expiry, Strike=strike, Type=type, .before = tradeTime)
        files[[f]] <- df
    }
    df <- do.call(rbind, files) %>% rename(Date=tradeTime, Open=openPrice,  High=highPrice, Low=lowPrice, , Close=lastPrice, IV=impliedVolatility) %>% mutate(Date=as.Date(Date, format="%m/%d/%Y"), IV=as.numeric(sub("%", "", IV))) %>% arrange(Date)
    df$ATM <- ifelse(df$Strike == round(df$baseLastPrice, 1), TRUE, FALSE)
    SPY <- df
    # 30-days IV
    IV30 <- SPY %>% filter(ATM==TRUE) %>% group_by(Date) %>% reframe(IVm = mean(IV))
}

# Dolthub option data
{
    # Only January 2024
    dolthub_2024 <- read_csv("/home/marco/trading/HistoricalData/Dolthub/sample_2024.csv") %>% 
        rename(Date=date, Symbol=act_symbol, IV=vol) %>% 
        mutate(Date=as.Date(Date), expiration=as.Date(expiration), dte = expiration-Date) #%>% filter(call_put=="Put" & abs(round_to_nearest(delta, 0.05)) == 0.5)
    dolthub_2024 <- inner_join(dolthub_2024, stock_price_data, by=c("Symbol", "Date"))
    dolthub_2024 <- inner_join(dolthub_2024, Stocks_Info, by=c("Symbol"))
    dolthub_2024 <- dolthub_2024 %>% mutate(
                                                VRP = IV - RV,
                                                VRPlog = log(IV / RV),
                                                VRPadj = VRPlog / HV1,
                                                VRPvega = vega * (IV - RV)
                                                )
    
    # Generate volatility data from dolthub options data 
    # (I want to know if I can recreate volatility summary similar to barchart data like https://www.barchart.com/stocks/quotes/AAPL/options-history)
    # I select option close to 0.5 delta, and weight all contracts according to distance from expiration
    {
        dir <- "/home/marco/trading/HistoricalData/Dolthub/Split_by_stock/"
        files <- list.files(dir, pattern = "*.csv")
        Dolthub_vols_list <- list()
        for(f in files){
            n <- sub("sample_", "", f) %>% sub(".csv", "", .)
            if(!n %in% names(Price_data_stocks))
                next
            print(n)
            # Load the file and calculate dte and distance from 30 days
            df_file <- fread(paste0(dir, f)) %>% rename(Date=date) %>% 
                mutate(Date=as.Date(Date), expiration=as.Date(expiration), dte = as.numeric(expiration-Date), vol = case_when(vol == -1 ~ NA, TRUE ~ vol)) %>% 
                mutate(delta_ = abs(round_to_nearest(delta, 0.1)), dist = 1/(abs(dte - 30)+1))
            # Extract ATM options and calculate weights
            df_w <- df_file %>% group_by(Date) %>%  filter(delta_==0.5) %>% 
                group_by(Date, expiration) %>% reframe(M=mean(vol), dist=first(dist), vega=first(vega), bid=first(bid), ask=first(ask))  %>% 
                group_by(Date) %>% mutate(W = (dist / sum(dist))) 
            # ATm weighted means and term structure slopes
            df_iv <- group_by(df_w, Date) %>% reframe(IV = sum(M*W, na.rm=T), Slope = log(last(M)/first(M)), vega=first(vega), bid=first(bid), ask=first(ask))
            # Volatility smile skew
            df_skew <- df_file %>% filter(delta_ < 0.50) %>% group_by(Date, expiration, call_put) %>% reframe(M=mean(vol), dist=first(dist)) %>% # average of calls and puts by contract and date
                group_by(Date) %>% mutate (W = dist / sum(dist)) %>% # normalize dte distance
                group_by(Date, expiration) %>% reframe(S = log(last(M) / first(M)), W=first(W)) %>% # expirations skews
                group_by(Date) %>% reframe(Skew = sum(S*W)) # weighed average of expirations skews
            df <- inner_join(df_iv, df_skew, by="Date") %>% arrange(Date)
            df <- inner_join(df, Price_data_stocks[[n]], by="Date") %>% 
                mutate(IV = case_when(IV == 0 ~ NA, TRUE ~ IV), 
                       VRP = IV - RV,  VRPlog = log(IV / RV),   VRPadj = VRPlog / HV1, VRPvega = vega * VRP) %>% arrange(Date)
             
            # Ignore small files (less than 100 observations)
            if(nrow(df) < 50) 
                next
            Dolthub_vols_list[[n]] <- df
        }
        
        Dolthub_vols_chains <- do.call(rbind, Dolthub_vols_list) %>% inner_join(., Stocks_Info, keep=FALSE, by="Symbol")
        write_csv(Dolthub_vols_chains, "/home/marco/trading/HistoricalData/Barchart/Options/Dolthub_vols_chains.csv")
    }
    
    
    # Generate ATM straddles (you need the lists Price_data_stocks and Stocks_Info, see above)
    # PROBABLY INCORRECT AS DOLTHUB DATA PRESENTS HOLES
    {
        Straddles <- list()
        dir <- "/home/marco/trading/HistoricalData/Dolthub/Split_by_stock//"
        for(f in list.files(dir, pattern = "*.csv")){
            df <- fread(paste0(dir, f)) %>% as.data.frame() %>% rename(Date=date, Symbol=act_symbol) %>% 
                  mutate(Date=as.Date(Date), expiration=as.Date(expiration), dte = expiration-Date)
            symbol <- as.character(head(df$Symbol, 1))
            print(symbol)
            if(symbol %in% names(Straddles)) next
            prices <- Price_data_stocks[[symbol]]
            if(is.null(prices) || nrow(Price_data_stocks[[symbol]]) < 500 | !symbol %in% Stocks_Info$Symbol) next
            df <- inner_join(df, prices, by=c("Date", "Symbol")) 
            if(nrow(df) == 0) next
            stdls <- df %>% 
                mutate(diff = abs(Close - strike)) %>% # I think Close is more correct than AdjClose (we are before dividends split)
                group_by(Symbol, Date, expiration, call_put) %>% mutate(m=min(diff), ATM=m==diff) %>% 
                group_by(Symbol, Date, expiration, strike) %>% reframe(straddle = sum(ask), spread=sum(ask-bid)/2, IV = sum(vol), delta=sum(delta), gamma=sum(gamma), theta=sum(theta), vega=sum(vega), rho=sum(rho), dte=first(dte), ATM=first(ATM), Close=first(Close)) %>% 
                mutate(ID=paste(Symbol, expiration, strike, sep="_")) %>% arrange(Date) %>% 
                group_by(ID) %>% mutate(Return=log(lead(straddle)/straddle), Cost=spread/straddle+lead(spread)/lead(straddle)) %>% # Here Return is the future return, in case you are entering the position now
                filter(ATM==TRUE)
            stdls <- cbind(stdls, Stocks_Info %>% filter(Symbol == symbol) %>% dplyr::select(-Symbol)) 
            stdls <- inner_join(stdls %>% dplyr::select(-Close), Price_data_stocks[[symbol]], by=c("Symbol", "Date")) %>% mutate(VRP = IV - RV, VRPlog = log(IV / RV))  %>% filter(!is.infinite(VRPlog)) %>% arrange(Date) 
            Straddles[[symbol]] <- stdls
        }
        straddles <- do.call(rbind, Straddles)
        # Plots
        straddles %>% group_by(Symbol) %>% reframe(VRP=median(VRPlog, na.rm=T), Class=first(`Sector`)) %>% ggplot(aes(y=VRP, x=Class, group=Class)) + geom_boxplot() + geom_hline(yintercept = 0)+ theme(axis.text.x = element_text(angle = 45))
        straddles %>% filter(!is.infinite(Return)) %>% mutate(dte=round(dte/10)) %>% group_by(Symbol, dte) %>% reframe(Ms=median(VRPlog, na.rm=T)) %>% group_by(dte) %>% reframe(M=mean(Ms, na.rm=T), S=sd(Ms, na.rm=T)/sqrt(n()*2), N=n()) %>% filter(N>100) %>% ggplot(aes(x=dte, ymin=M-S, ymax=M+S)) + geom_errorbar(width=0.5) + geom_hline(yintercept = 0)    
    }
   
}

# Dolthub volatility data single file (BEWARE, only 3 days per week, VRPlog might be different)
{
    Dolthub_vols <- read_csv("/home/marco/trading/HistoricalData/Dolthub/post-no-preference_options_master_volatility_history.csv.gz")
    Dolthub_vols <- Dolthub_vols %>% rename(Symbol=act_symbol, Date=date) %>% group_by(Symbol) %>% 
        mutate(rv_current = lead(hv_current, 13), VRPlog = log(iv_current / rv_current)) # 13 because we only have mondays, wednesdays and fridays. This can be an issue for this data
    Dolthub_vols <- full_join(Dolthub_vols, Stocks_Info, by="Symbol") %>% ungroup() %>% filter(!is.na(Name) & !is.na(Date))
    Dolthub_vols <- full_join(Dolthub_vols, stock_price_data, by=c("Symbol", "Date")) 
    write_csv(Dolthub_vols, "/home/marco/trading/HistoricalData/Barchart/Options/Dolthub_vols.csv")
    Dolthub_balance_sheet_equity <- read_csv("/home/marco/trading/HistoricalData/Dolthub/post-no-preference_earnings_master_balance_sheet_equity.csv.gz")
    Dolthub_balance_sheet_assets <- read_csv("/home/marco/trading/HistoricalData/Dolthub/post-no-preference_earnings_master_balance_sheet_assets.csv.gz")
    
    
}

# ORATS core data loading
{
    # function for loading an ORATS core data file and returning a subset of columns
    quiet_read_csv <- purrr::quietly((.f = read_csv))
    quiet_fread <- purrr::quietly((.f = fread))
    
    load_orats_day <- function(filename, cols_to_extract) {
        print(filename)
        # quiet_read_csv(glue::glue("/media/marco/Elements/ORATS/cores/{filename}")) #%>%
        quiet_fread(glue::glue("/media/marco/Elements/ORATS/cores/{filename}")) %>%
            purrr::pluck("result")  %>%   select(all_of(cols_to_extract)) %>% mutate(across(3:ncol(.), as.numeric))
    }
    
    cols_to_extract <- c('ticker', 'tradeDate', 'pxAtmIv', 
                         "mktCap", "beta1m", "beta1y",
                         "straPxM1", "straPxM2",
                          "cVolu",  "cOi" , "pVolu",  "pOi", "avgOptVolu20d", 
                         "atmIvM1", "dtExM1",  "atmIvM2", "dtExM2", "iv30d", "volOfIvol", 
                         "clsHv20d", "clsHv252d",
                         "contango", "slope", "px1kGam", "confidence", "error"
                         )
    # Loads all ORATS core files, selecting interesting columns
    dir <- "/media/marco/Elements/ORATS/cores/"
    files <- list.files(dir, pattern = "orats_core_202..*gz")
    ORATS_core <- files %>% purrr::map_df(.f = load_orats_day, cols_to_extract)
    # Calculate price returns
    ORATS_core <- ORATS_core  %>% mutate(tradeDate=as.Date(tradeDate)) %>% mutate(pxAtmIv = case_when(pxAtmIv < 0 ~ 0, TRUE ~ pxAtmIv)) %>% group_by(ticker) %>% arrange(tradeDate) %>% mutate(retAtmIv = c(0, diff(log(pxAtmIv))), .after = pxAtmIv)
    # Remove returns > 0.05, as they are usually from stock splits
    ORATS_core <- ORATS_core  %>% mutate(retAtmIv = case_when(abs(retAtmIv) > 0.1  | retAtmIv == 0 ~ NA, TRUE ~ retAtmIv)) 
    # Calculate cumulative price returns from current date to expiry
    ORATS_core <- ORATS_core  %>% mutate(cumRetAtmIv = map_dbl(1:n(), ~ sum(retAtmIv[(.x+1):min(.x + dtExM1[.x] - 1, n())])), .after = retAtmIv)  #%>% mutate(cumRetAtmIv = case_when(dtExM1 == 1 ~ NA, TRUE ~ cumRetAtmIv))
    # Calculate expected straddle returns, ignore when straddle price is bigger than stock price
    ORATS_core <- ORATS_core %>% mutate(straRetM1 = abs(cumRetAtmIv) - straPxM1 / pxAtmIv, straRetM1 = case_when(straPxM1 > pxAtmIv ~ NA, TRUE ~ straRetM1)) %>% ungroup
    write_csv(ORATS_core, "/home/marco/trading/HistoricalData/ORATS/ORATS_core.csv")
}

# Various correlations with SPY (SPY is a data.frame with barchart vol data and historical volatilities)
{
    a <- select(Barchart_vols_stocks, Symbol, Date, HV1) %>% pivot_wider(names_from = Symbol, values_from = HV1)
    b <- merge(a, SPY %>% select(Date, HV1) %>% rename(SPY=HV1), by="Date")
    hv1 <- cor(b[,-1], use="pairwise.complete.obs")[,"SPY"]
    a <- select(Barchart_vols_stocks, Symbol, Date, IV) %>% pivot_wider(names_from = Symbol, values_from = IV)
    b <- merge(a, SPY %>% select(Date, IV) %>% rename(SPY=IV), by="Date")
    iv <- cor(b[,-1], use="pairwise.complete.obs")[,"SPY"] 
    a <- select(Barchart_vols_stocks, Symbol, Date, ReturnPrice) %>% pivot_wider(names_from = Symbol, values_from = ReturnPrice)
    b <- merge(a, SPY %>% select(Date, ReturnPrice) %>% rename(SPY=ReturnPrice), by="Date")
    ret <- cor(b[,-1], use="pairwise.complete.obs")[,"SPY"] 
    SPY_correlations <- data.frame(Symbol=names(ret), corHV1=hv1, corIV=iv, corReturn=ret)
    write_csv(SPY_correlations, "/home/marco/trading/HistoricalData/Barchart/Options/SPY_correlations.csv")
    
}

# Clustering
{
    # the hard way
    library(dbscan)
    library(Rtsne)
    PC <- 10 # The number of PCA factor to use, keep it low to avoid overfitting
    EPS <- 1 # Play with this to get the number of pairs you want  
    good_symbols -> ... # all non NA containing symbols
    Returns <- stocks %>% filter(Symbol %in% good_symbols & between(Date, "2023-01-01", "2024-01-01")) %>% select(Date, Symbol, ReturnPrice) %>% pivot_wider(names_from = Symbol, values_from = ReturnPrice) %>% arrange(Date) 
    pca <- prcomp( Returns[,-1] %>%  t, center = TRUE, scale. = TRUE) # run PCA
    X <- pca$x[,1:PC]; # Extract PCA factors
    rtsne <- Rtsne(X, check_duplicates = TRUE)$Y # Run t-SNE, some people say it is bad and you should only use PCA factors, I don't know
    optic_res <- optics(rtsne, minPts = 2) # Run optics, this is the pre-clustering
    Clusters <- extractDBSCAN(optic_res, eps_cl = 1) # Run DBscan clustering
    hullplot(rtsne, Clusters) # visualize clusters
    clusters <- data.frame(Symbol = good_symbols[-1], Cluster = Clusters$cluster)
    # the easy way
    a <- lapply(Price_data_stocks, function(df) select(df, Date, ReturnPrice))
    names(a) <- names(Price_data_stocks)
    b <- Reduce(function(...) full_join(..., by = "Date"), a) %>% arrange(Date)
    z <- cor(b[,-1], use="pairwise.complete.obs")
    rownames(z) <- names(Price_data_stocks)
    colnames(z) <- names(Price_data_stocks)
    z[is.na(z)] <- 0 # careful
    d <- as.dist(1 - z)
    tree <- hclust(d, method="complete")
    dend <- as.dendrogram(tree)
    clusters <- cutree(dend, k=50)
}


# Plot some general observations from barchart volatility data  (or other data packages) 
{
    # Load saves Stocks and ETFs data
    Barchart_vols_stocks <- read_csv("/home/marco/trading/HistoricalData/Barchart/Options/Barchart_vols_stocks.csv")
    Dolthub_vols <- read_csv("/home/marco/trading/HistoricalData/Barchart/Options/Dolthub_vols.csv")
    Dolthub_vols_chains <- read_csv("/home/marco/trading/HistoricalData/Barchart/Options/Dolthub_vols_chains.csv")
    # Barchart_vols_stocks and Dolthub_vols_chains (calculated by me using option chains data) seems more similar than Barchart_vols_stocks and Dolthub_vols, maybe because with Dolthub_vols I used the already provided "hv_current" see above and not my own volatility
    #ETFs <- readRDS("/home/marco/trading/Systems/Options/ETFs.RDS")
    
    ## ETFs
    {
    # Keep only ETFs with < 20% NAs in ImpVol after 2021 (most data have NAs in the first years)
    reduced_etfs <- ETFs %>% group_by(Symbol) %>% filter(Date > "2021-01-01") %>% filter(sum(is.na(ImpVol))/length(ImpVol) < 0.2) %>% ungroup
    reduced_etfs$Vega <- unlist(greeks(bscall(reduced_etfs$Close, reduced_etfs$Close, reduced_etfs$ImpVol, r=0, tt=30/365, d=0))["Vega",] + 
                                    greeks(bsput(reduced_etfs$Close, reduced_etfs$Close, reduced_etfs$ImpVol, r=0, tt=30/365, d=0))["Vega",])
    reduced_etfs <- reduced_etfs %>% mutate(Profit = Vega * (ImpVol - RealVol))
    # VRP by asset class, AUM and NAV
    reduced_etfs %>% group_by(Symbol) %>% reframe(VRP=median(VRPlog, na.rm=T), Class=first(`Asset Class`)) %>% ggplot(aes(y=VRP, x=Class)) + geom_boxplot() + geom_hline(yintercept = 0)
    reduced_etfs %>% group_by(Symbol) %>% reframe(VRP=median(VRPlog, na.rm=T), Class=first(`AUM`))  %>% mutate(G=ntile(Class, 10))%>% ggplot(aes(y=VRP, x=factor(G))) + geom_boxplot() + geom_hline(yintercept = 0) + theme(axis.text.x = element_text(angle = 45))
    reduced_etfs %>% group_by(Symbol) %>% reframe(VRP=median(VRPlog, na.rm=T), Class=first(`NAV`))  %>% mutate(G=ntile(Class, 10))%>% ggplot(aes(y=VRP, x=factor(G))) + geom_boxplot() + geom_hline(yintercept = 0) + theme(axis.text.x = element_text(angle = 45)) 
    reduced_etfs %>% group_by(Symbol) %>% reframe(VRP=median(VRPlog, na.rm=T), Class=first(`Mgmnt Fee`))  %>% mutate(G=ntile(Class, 10))%>% ggplot(aes(y=VRP, x=factor(G))) + geom_boxplot() + geom_hline(yintercept = 0) + theme(axis.text.x = element_text(angle = 45))
    }
    
    ## Stocks
    # From Barhchart data, Keep only Stocks with < 20% NAs in ImpVol betweem 2021 and 2024 (most data have NAs in the first years)
    stocks <- Barchart_vols_stocks %>% group_by(Symbol) %>% filter(Date > "2020-01-01") %>% filter(sum(is.na(IV))/length(IV) < 0.1) %>% ungroup %>% filter(VRPlog < Inf)
    # Recent VRPs
    Barchart_vols_ETFs %>% filter(Date > "2022-01-01") %>%  group_by(Symbol) %>% reframe(M=median(VRPlog, na.rm=T), S=mad(VRPlog, na.rm=T)/sqrt(n())*2, N=n()) %>% View
    # VRP by class
    classv <- "Sector"
    stocks %>% group_by(Symbol) %>% reframe(VRP=median(VRPlog, na.rm=T), Class=first(!!rlang::sym(classv) )) %>% ggplot(aes(y=VRP, x=Class)) + geom_boxplot() + geom_hline(yintercept = 0)+ theme(axis.text.x = element_text(angle = 45))
    stocks %>% mutate(Decile = ntile((`Market Cap`), 5)) %>% group_by(Symbol, Decile) %>% reframe(VRP=median(VRPlog, na.rm=T)) %>% ggplot(aes(y=VRP, x=Decile, group=Decile)) + geom_boxplot() + geom_hline(yintercept = 0)+ theme(axis.text.x = element_text(angle = 45)) 
    stocks %>% mutate(Decile = ntile((`Market Cap`), 5)) %>% group_by(Symbol, Decile, Year=year(Date)) %>% reframe(VRP=median(VRPlog, na.rm=T))  %>% group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    # VRP by price and returns
    stocks %>% mutate(Decile = ntile(AdjClose, 5)) %>% group_by(Symbol, Decile, Year=year(Date)) %>% reframe(VRP=median(VRPlog, na.rm=T))  %>% group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    stocks %>% mutate(Decile = ntile(ReturnPrice %>% abs %>% na.locf0() %>% SMA(20) %>% lag, 5)) %>% group_by(Symbol, Decile, Year=year(Date)) %>% reframe(VRP=median(VRPlog, na.rm=T))  %>% group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    # VRP by some vol prediction (like IV, HV1, log(IV/HV1), Momentum...)
    stocks %>% group_by(Symbol) %>% mutate(Decile = ntile(lag(IV, 1), 10)) %>% 
        group_by(Symbol, Decile, Year=year(Date))  %>% reframe(VRP=median(VRPlog, na.rm=T))  %>%
        group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    # VRP by vol of vol
    stocks %>% group_by(Symbol) %>% mutate(VolVol = runSD(log(HV1/lag(HV1)) %>% na.locf(na.rm=F), 21) %>% lag) %>% 
        mutate(Decile = ntile(VolVol, 10)) %>%  group_by(Symbol, Decile, Year=year(Date)) %>% reframe(VRP=median(VRPlog, na.rm=T)) %>% 
        group_by(Decile, Year)  %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar()+ facet_wrap(~Year)    
    # VRP by week day
    stocks %>% group_by(Symbol, Decile=wday(Date), Year=year(Date)) %>% reframe(VRP=median(VRPlog, na.rm=T))  %>% 
        group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    # VRP by cost (dolthub data only)
    stocks %>% mutate(Cost = (bid-ask)/bid, Decile = ntile(Cost, 5)) %>% group_by(Symbol, Decile, Year=year(Date)) %>% reframe(VRP=median(VRPlog, na.rm=T))  %>% group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    # VRP by SPY correlation
    stocks %>% ungroup %>% full_join(., SPY_correlations, by="Symbol")%>% mutate(Decile = ntile(corReturn, 5)) %>% group_by(Symbol, Decile, Year=year(Date)) %>% reframe(VRP=mean(VRPlog, na.rm=T)) %>% filter(!is.nan(VRP)) %>% group_by(Decile, Year) %>% reframe(M=mean(VRP), S=sd(VRP)/sqrt(n())*2, N=n()) %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year) 
    # VRP by higher moments (not much here)
    stocks  %>% group_by(Symbol) %>% mutate(Skew = rollapply(ReturnPrice, width=100, skew,  fill=NA, align="right") %>% lag) %>% 
        mutate(Decile = ntile(Skew, 10)) %>%  group_by(Symbol, Decile, Year=year(Date)) %>% reframe(VRP=median(VRPlog, na.rm=T)) %>% 
        group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar()+ facet_wrap(~Year)     
    stocks %>% group_by(Symbol) %>% mutate(CR = carver_ratio(Return, n=21),  Decile = ntile(lag(CR), 10)) %>% group_by(Decile) %>% reframe(M=mean(VRPlog), S=sd(VRPlog)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar()
    stocks %>% group_by(Symbol) %>% mutate(CR = carver_ratio(Return, n=21),  Decile = ntile(lag(CR), 10)) %>% group_by(Decile, Sector) %>% reframe(M=mean(VRPlog), S=sd(VRPlog)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar()  + facet_wrap(~Sector, scales = "free") 
    # Using ad hod clustering (see stocks example for clustering)
    stocks %>% full_join(clusters, by="Symbol") %>% group_by(Symbol) %>% group_by(Date, Cluster) %>% reframe(M=mean(VRPlog), S=sd(VRPlog)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar()
    # IV pacf autocorrelation by market cap (or something else)
    a <- stocks %>% mutate(Decile = ntile((`Market Cap`), 5)) %>% group_by(Decile) %>% reframe(Pacf=unlist(as.data.frame(pacf(IV)$acf)))
    a$x <- rep(1:55,5); a$Pacf <- as.vector(a$Pacf)
    ggplot(a) + geom_bar(aes(x, Pacf), stat="identity") + facet_wrap(~Decile)
}

# Plot some general observations from ORATS core data 
{
    ORATS_core <- read_csv("/home/marco/trading/HistoricalData/ORATS/ORATS_core.csv")
    # Straddles return by market cap - moments
    ORATS_core %>% mutate(Decile = ntile(mktCap, 5)) %>% group_by(ticker, Decile, Year=year(tradeDate)) %>% reframe(VRP=median(straRetM1/(dtExM1+1) , na.rm=T))  %>% group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    ORATS_core %>% mutate(Decile = ntile(mktCap, 5)) %>% group_by(ticker, Decile, Year=year(tradeDate)) %>% reframe(VRP=mad(straRetM1/(dtExM1+1), na.rm=T))  %>% group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    ORATS_core %>% mutate(Decile = ntile(mktCap, 5)) %>% group_by(ticker, Decile, Year=year(tradeDate)) %>% reframe(VRP=skewness(straRetM1/(dtExM1+1) %>% replace(.,is.infinite(.), NA), na.rm=T))  %>% group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    ORATS_core %>% mutate(Decile = ntile(mktCap, 5)) %>% group_by(ticker, Decile, Year=year(tradeDate)) %>% reframe(VRP=kurtosis(straRetM1/(dtExM1+1) %>% replace(.,is.infinite(.), NA), na.rm=T))  %>% group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    # Straddles return by market cap - total distribution
    ORATS_core %>% mutate(Decile = factor(ntile(mktCap, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return by dte
    ORATS_core %>% filter(dtExM1<=20)  %>% ggplot(aes(x=straRetM1/(dtExM1+1))) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + facet_wrap(~dtExM1) + xlim(c(-0.05,0.05))
    # Straddles return by price
    ORATS_core %>% mutate(Decile = factor(ntile(pxAtmIv, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return by beta
    ORATS_core %>% mutate(Decile = factor(ntile(beta1y, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return by iv30 - inter ticker and intra ticker 
    ORATS_core %>% mutate(Decile = factor(ntile(iv30d, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    ORATS_core %>% group_by(ticker) %>% mutate(Decile = factor(ntile(iv30d, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return by clsHv20d - inter ticker and intra ticker (almost identical to above iv30)
    # Straddles return by volofIvol - inter ticker  only
    ORATS_core %>% mutate(Decile = factor(ntile(volOfIvol, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return by contango - inter ticker and intra ticker 
    ORATS_core %>%  mutate(Decile = factor(ntile(contango, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    ORATS_core %>% group_by(ticker) %>% mutate(Decile = factor(ntile(contango, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return by slope - inter ticker only
    ORATS_core %>% mutate(Decile = factor(ntile(slope, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return by px1kGam - inter ticker and intra ticker 
    ORATS_core %>%  mutate(Decile = factor(ntile(px1kGam, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    ORATS_core %>% group_by(ticker) %>% mutate(Decile = factor(ntile(px1kGam, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return by confidence - inter ticker  only
    ORATS_core %>% mutate(Decile = factor(ntile(confidence, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return by error - inter ticker  only
    ORATS_core %>% mutate(Decile = factor(ntile(error, 5))) %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return PACF autocorrelation by dte (probably it's just VRP making straddles correlated)
    ORATS_core %>% arrange( ticker, dtExM1, tradeDate ) %>% group_by(dtExM1) %>% filter(n()>10000) %>% reframe(Acf = pacf(na.omit(straRetM1/(dtExM1+1)), plot = F, lag.max = 1)$acf[[1]], n()) %>% ggplot(aes(dtExM1, Acf)) + geom_point()
    # Straddles return by month day
    ORATS_core %>% mutate(Decile = mday(tradeDate)) %>% group_by(ticker, Decile, Year=year(tradeDate)) %>% reframe(VRP=median(straRetM1/(dtExM1+1) , na.rm=T))  %>% group_by(Decile, Year) %>% reframe(M=mean(VRP, na.rm=T), S=sd(VRP, na.rm=T)/sqrt(n())*2, N=n()) %>% na.omit %>% ggplot(aes(x=Decile, ymin=M-S, ymax=M+S)) + geom_errorbar() + facet_wrap(~Year)
    # Straddles return by stock return - inter ticker and intra ticker 
    ORATS_core  %>%  mutate(Decile = factor(ntile(retAtmIv %>% na.locf(na.rm = F) , 5))) %>% na.omit %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    ORATS_core  %>% group_by(ticker) %>%  mutate(Decile = factor(ntile(retAtmIv %>% na.locf(na.rm = F) , 5))) %>% na.omit %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    # Straddles return by stock price momentum - inter ticker and intra ticker ARRANGE IS IMPORTANT!!!
    ORATS_core %>% arrange(ticker, tradeDate) %>%  mutate(Decile = factor(ntile(pxAtmIv %>% na.locf(na.rm = F) %>% RSI2(., 60, maType=EMA), 5))) %>% na.omit %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
    ORATS_core %>% group_by(ticker) %>% filter(n()>252) %>% arrange(ticker, tradeDate) %>%  mutate(Decile = factor(ntile(pxAtmIv %>% na.locf(na.rm = F) %>% RSI2(., 60, maType=EMA), 5))) %>% na.omit %>% ggplot(aes(x=straRetM1/(dtExM1+1), color=Decile, group=Decile)) + geom_density(linewidth=1) + geom_vline(xintercept = 0) + scale_color_colorblind() + xlim(c(-0.05,0.05))
}


# Dolthub single stock playing with  (SPY as example)
{
    ticker <- "SPY"
    data_opt <- read_csv(paste0("/home/marco/trading/HistoricalData/Dolthub/Split_by_stock//sample_", ticker, ".csv"), show_col_types = F) %>% mutate(mid = (bid+ask)/2, cost = (ask-bid)/ask, id = paste(act_symbol, expiration, strike, call_put, sep="_"), wday = lubridate::wday(date, label=T), dte = as.integer(expiration-date))
    vol_shift <- 21
    data_price <- read_csv(paste0("/home/marco/trading/HistoricalData/Barchart/Options/YahooPrice/Stocks/", ticker, ".csv"), show_col_types = F) %>% 
        rename(date=Date, AdjClose = `Adj Close`) %>% 
        mutate(ReturnPrice = log(AdjClose / lag(AdjClose)),                                                                                                                                                          
               ReturnPrice = replace_na(ReturnPrice, 0),
               Return1week = log(AdjClose / lag(AdjClose, 5)),
               Return6month = log(AdjClose / lag(AdjClose, 120)),
               HV1 = runSD(ReturnPrice, vol_shift) * sqrt(252), 
               HV2 = calculate_volatility(ReturnPrice, long_span = 252, short_span = vol_shift, period = 252),
               RV = lead(HV1, vol_shift))    
    data <- merge(data_opt, data_price, by="date") 
    data <- data %>% mutate(VRP = vol - RV, VRPlog = log(vol / RV), VRPprofit = 1/vega * (vol - RV), VRPprofit_ = (1/vega)/(RV*(365/dte)) * (vol^2 - RV^2))
    # IV vs RV
    data %>% na.omit%>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>% group_by(decile1 = date, decile2=round(delta_, 1)) %>% reframe(RV=first(RV), IV=mean(vol)) %>% ggplot(aes(x=decile1)) + geom_line(aes(y=RV), color="red")+ geom_line(aes(y=IV), color="blue") + facet_wrap(~decile2, scales = "free")
    # VRP (vega weighted)
    data %>% na.omit %>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>% 
        group_by(decile = round(delta_, 1), call_put) %>% reframe(Mean=median(VRPprofit), SD=sd(VRPprofit)/sqrt(n())) %>% ggplot(aes(x=decile, y=Mean, ymin=Mean-SD*2, ymax=Mean+SD*2, color=call_put)) + geom_line() + geom_errorbar(width=0.025)
    data %>% na.omit %>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>% 
        group_by(decile1 = round(delta_, 1), decile2 = round(dte / 10), call_put) %>% reframe(Mean=median(VRPprofit), SD=mad(VRPprofit)/sqrt(n())*2) %>% ggplot(aes(x=decile1, y=Mean, ymin=Mean-SD*2, ymax=Mean+SD*2, color=call_put)) + geom_line() + geom_errorbar(width=0.025)+ facet_wrap(~decile2)  
    # Volatility smile
    data %>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>% group_by(decile = round(delta_, 1), call_put) %>% reframe(Mean=median(vol), SD=sd(vol)/sqrt(n())) %>% ggplot(aes(x=decile, y=Mean, ymin=Mean-SD*2, ymax=Mean+SD*2, color=call_put)) + geom_line() + geom_errorbar(width=0.025)    
    data %>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>% group_by(decile1 = round(delta_, 1), decile2 = round(dte / 10), call_put) %>% reframe(Mean=median(vol), SD=sd(vol)/sqrt(n())) %>% ggplot(aes(x=decile1, y=Mean, ymin=Mean-SD*2, ymax=Mean+SD*2, color=call_put)) + geom_line() + geom_errorbar(width=0.025) + facet_wrap(~decile2)   
    # Weekend effect?
    data_we <- mutate(data, yw = yearweek(date, week_start=1))
    data_we %>% filter(call_put=="Call") %>% group_by(id, yw)  %>% 
        reframe(Time=-c(NA, diff(dte)), Diff=c(NA, diff(mid))/lag(mid)*100, Day=wday, delta=round(delta, 1)) %>% na.omit %>% filter(Diff!=0) %>% group_by(Time) %>% reframe(Mean=median(Diff), SD=mad(Diff)/sqrt(n()), N=n()) 
    # Weekend effect with straddles
    {
    a <- data_opt %>% mutate(delta_ = case_when(call_put=="Call" ~ abs(delta), TRUE ~ 1-delta)) %>%  mutate(delta_ = abs(round_to_nearest(delta, 0.05))) %>% filter(call_put=="Call") %>% select(date, expiration, strike, mid, delta_, vega) 
    b <- data_opt %>% mutate(delta_ = case_when(call_put=="Put" ~ abs(delta), TRUE ~ 1-delta)) %>%  mutate(delta_ = abs(round_to_nearest(delta, 0.05))) %>% filter(call_put=="Put") %>% select(date, expiration, strike, mid, delta_, vega) 
    straddles <- full_join(a, b, by=c("date", "expiration", "strike")) %>% mutate(straddle=mid.x+mid.y, wday=lubridate::wday(date, label=TRUE), id=paste(expiration,strike,sep="_"))
    straddles <- straddles %>% mutate(dte=as.integer(expiration-date)) %>%  group_by(id) %>% mutate(vega=(vega.x+vega.y)/2, profit=c(NA, diff(straddle))/vega)  # profit in dollar terms
    straddles %>% filter(delta_.x==0.5, delta_.y==0.5 & profit != 0) %>% group_by(wday) %>% na.omit %>% reframe(M=mean(profit), sd=sd(profit)/sqrt(n())*2, n=n()) %>% filter(wday %in% c("Mon","Wed","Fri")) 
    }
    # VRP by dte (not totally correct, as the RV should be calculated over the dte)
    data %>% group_by(dte) %>% reframe(M=median(VRPlog, na.rm=T), S=mad(VRPlog, na.rm=T)/sqrt(n()), N=n()) %>% arrange(dte) %>% filter(N>1000) %>% ggplot(aes(x=dte, y=M, ymin=M-S*2, ymax=M+S*2)) + geom_line(color="blue") + geom_errorbar(color="darkgray") + geom_point()
}

#  ORATS api data single stock playing with (SPY as example)
{
    strikes_f <- read_csv("/home/marco/ORATS/strikes/IWM/IWM_.csv")
    df_file <- strikes_f %>% mutate(delta_ = abs(round_to_nearest(delta, 0.1)), dist = 1/(abs(dte - 30)+1))
    df_w <-  df_file %>% group_by(tradeDate) %>%  filter(delta_==0.5) %>% group_by(tradeDate, expirDate) %>% reframe(M=mean(smvVol), dist=first(dist), vega=first(vega), value=mean(callValue+putValue))  %>%     group_by(tradeDate) %>% mutate(W = (dist / sum(dist))) 
    df_iv <- group_by(df_w, tradeDate) %>% reframe(IV = sum(M*W, na.rm=T), Slope = log(last(M)/first(M)), vega=first(vega), value=first(value))
    # Volatility smile
    strikes_f %>% mutate(IV=putMidIv, delta_ = round_to_nearest(1-delta, 0.1), dte_ = round(dte / 30)) %>% group_by(delta_, dte_) %>% reframe(M=median(IV, na.rm=T), S=mad(IV, na.rm=T)/sqrt(n()), N=n()) %>% ggplot(aes(delta_, y=M, ymin=M-S*2, ymax=M+S*2)) + geom_line(color="blue") + geom_errorbar(width=0.05) + facet_wrap(~dte_)
    # Straddles over weekend analysis (by IV)
    strikes_f <- read_csv("/home/marco/ORATS/strikes/IWM/IWM_.csv") 
    cores_f <- core_df %>% filter(ticker == "IWM")
    hv <- strikes_f %>% dplyr::select(tradeDate,spotPrice ) %>% group_by(tradeDate) %>% reframe(spotPrice=first(spotPrice)) %>% 
        mutate(ReturnPrice =log(spotPrice/lag(spotPrice)), HV = runSD(ReturnPrice, 7) * sqrt(252), RV = lead(HV, 7)) %>% dplyr::select(-spotPrice)    
    ff <- full_join(strikes_f, hv, by="tradeDate") %>% mutate(IV = (callMidIv+putMidIv)/2) %>% 
        mutate(VRP = IV - RV, VRPlog = log(IV / RV), wd = lubridate::wday(tradeDate, label = TRUE), delta_ = round_to_nearest(delta, 0.1))
    ff %>% filter(delta_==0.5 & dte == 1) %>% group_by(wd) %>% reframe(M=mean(VRPlog, na.rm=T), S=2*sd(VRPlog, na.rm=T)/sqrt(n()), N=n())
    # Straddles over weekend analysis (by price)
    strikes_f <- read_csv("/home/marco/ORATS/strikes/SLV/_.csv") 
    ff <- mutate(strikes_f, id=paste(strike, expirDate, sep="_"), .after = ticker)
    ff <- mutate(ff, delta_ = round_to_nearest(delta, 0.1), wd = lubridate::wday(tradeDate, label=TRUE), value=(callAskPrice+callBidPrice)/2+(putAskPrice+putBidPrice)/2, cost=(callAskPrice-callBidPrice)+(putAskPrice-putBidPrice), .after = ticker)
    ff <- ff %>% group_by(id) %>% mutate(profit = c(diff(value), 0), profit_pct = profit / spotPrice * 100, .after = ticker)
    ff %>% filter(delta_ == 0.5 & dte <= 7) %>% group_by(wd, dte) %>% reframe(M=mean(profit, na.rm=T), S=sd(profit, na.rm=T)/sqrt(n()), N=n()) %>% ggplot(aes(x=wd, ymin=M-S*2, ymax=M+S*2)) + geom_errorbar(width=0.5) + facet_wrap(~dte) + geom_hline(yintercept = 0)
    ff %>% filter(delta_ == 0.5 & dte == 5) %>% group_by(wd) %>% mutate(PnL = cumsum(-profit)) %>% ggplot(aes(tradeDate, PnL, color=wd)) + geom_line(linewidth=2) + geom_point(color="black")
    # Straddles over weekend single backtest
    ff <- filter(strikes_f, tradeDate >= "2020-01-01") %>% 
        select(ticker, tradeDate, strike, expirDate, callAskPrice, callBidPrice, putAskPrice,putBidPrice ,  delta, dte)
    ff <- mutate(ff, id=paste(strike, expirDate, sep="_"), .after = ticker)
    ff <- mutate(ff, value=(callAskPrice+callBidPrice)/2+(putAskPrice+putBidPrice)/2, cost=(callAskPrice-callBidPrice)+(putAskPrice-putBidPrice), .after = ticker)
    ff <- ff %>% group_by(id) %>% mutate(profit=c(0, diff(value)), .after = ticker)
    ff <- ff %>%  mutate(delta_ = round_to_nearest(delta, 0.1), wd = lubridate::wday(tradeDate, label=TRUE),  .after = ticker)
    straddles_we <- ff %>% mutate(profit_ = -1 * lead(profit) - cost, profit_0 = -1 * lead(profit), profit_p = -1 * log(lead(value) / value)) %>% 
        filter(dte <= 7 & delta_ == 0.50 & wd == "Fri") %>% group_by(tradeDate) %>% reframe(profit_=mean(profit_, na.rm=T), profit_0=mean(profit_0, na.rm=T), profit_p=mean(profit_p, na.rm=T))  %>% ungroup %>% na.omit %>% mutate(PnL = cumsum(profit_), PnL0 = cumsum(profit_0))         
    straddles_we %>% ggplot(aes(tradeDate, PnL)) + geom_line() + geom_point() + geom_line(aes(y=PnL0), color="purple") + geom_point(aes(y=PnL0), color="purple")
}

# Straddles returns for ORATS data
{
    smvstrikes <- rbind(read_csv("/home/marco/trading/HistoricalData/ORATS/SPY/2020.csv"),
                    read_csv("/home/marco/trading/HistoricalData/ORATS/SPY/2021.csv"),
                    read_csv("/home/marco/trading/HistoricalData/ORATS/SPY/2022.csv"),
                    read_csv("/home/marco/trading/HistoricalData/ORATS/SPY/2023.csv"),
                    read_csv("/home/marco/trading/HistoricalData/ORATS/SPY/2024.csv"))
    smvstrikes <- read_csv("/media/marco/Elements/ORATS/smvstrikes/2024.csv")
    smvstrikes <- smvstrikes %>% rename(tradeDate = trade_date) %>% mutate(tradeDate = as.Date(tradeDate, format="%m/%d/%Y"), expirDate = as.Date(expirDate, format="%m/%d/%Y"), dte = as.integer(expirDate - tradeDate + 1))  %>% arrange(tradeDate)
    smvstrikes <- smvstrikes %>% filter(dte <= 50)
    smvstrikes <- mutate(smvstrikes, id=paste(ticker, strike, expirDate, sep="_"), delta_ = abs(round_to_nearest(delta, 0.1)), .after = ticker)
    smvstrikes <- mutate(smvstrikes, value=(cAskPx+cBidPx)/2+(pAskPx+pBidPx)/2, cost=(cAskPx-cBidPx)+(pAskPx-pBidPx), .after = id)
    smvstrikes <- smvstrikes %>% group_by(id) %>% arrange(tradeDate) %>% mutate(profit = c(diff(value), 0), profit_pct = profit / stkPx * 100, 
                                                                                profit_log = c(diff(log(value)), 0), 
                                                                                profit_cum = rev(cumsum(rev(profit))), profit_pct_cum = rev(cumsum(rev(profit_pct))), .after = ticker)
    smvstrikes_straddles <- smvstrikes %>% filter(delta_ == 0.5 & between(dte, 1, 90))
    smvstrikes_straddles %>% mutate(decile=round(dte/7))  %>%  ggplot(aes(x=profit_pct)) + geom_density() + facet_wrap(~decile)  + geom_vline(xintercept = 0) + xlim(c(-1,1))
    smvstrikes_w <-  smvstrikes %>% mutate(dist = abs(dte - 30)+1) %>% group_by(tradeDate) %>%  filter(delta_==0.5 & dte <= 30) %>% arrange(tradeDate, expirDate) %>% group_by(tradeDate, expirDate) %>% reframe(M=mean(smoothSmvVol), dist=first(dist), dte=first(dte)) %>% group_by(tradeDate) %>% mutate(W = (dist / sum(dist))) 
    smvstrikes_iv <- group_by(smvstrikes_w, tradeDate) %>% reframe(IV = sum(M*W, na.rm=T), Slope = log(last(M)/first(M))) %>% mutate(IVRank=ntile(IV, 10))
    smvstrikes_straddles_final <- full_join(smvstrikes_straddles, smvstrikes_iv, by="tradeDate")
}


# Simulate some strategies like E.Sinclair in Positional Options Trading
{
    
    # Good Straddle  
    gbm <- gbm_vec(10000, sigma = 0.2)
    option_sim_profit(gbm, type="call") -> a
    option_sim_profit(gbm, type="put") -> b
    profit <- (-a$profit-b$profit)*100
    hist(profit, 50); summary(profit)
    # Good Strangle
    gbm <- gbm_vec(10000)
    option_sim_profit(gbm, type="put", X = 70) -> a
    option_sim_profit(gbm, type="call", X = 130) -> b
    profit <- (-a$profit-b$profit)*100*1.68
    hist(profit, 50)
    # Bad Straddle Vol  
    gbm <- gbm_vec(10000, sigma = 0.7)
    option_sim_profit(gbm, type="call") -> a
    option_sim_profit(gbm, type="put") -> b
    profit <- (-a$profit-b$profit)*100
    hist(profit, 50)
    # Bad Strangle Vol
    gbm <- gbm_vec(10000, sigma = 0.7)
    option_sim_profit(gbm, type="put", X = 70) -> a
    option_sim_profit(gbm, type="call", X = 130) -> b
    profit <- (-a$profit-b$profit)*100*1.68
    hist(profit, 50)
    # Bad Straddle Drift  
    gbm <- gbm_vec(10000, mu = 0.2)
    option_sim_profit(gbm, type="call") -> a
    option_sim_profit(gbm, type="put") -> b
    profit_straddle <- (-a$profit-b$profit)*100
    # Bad Strangle Drift
    gbm <- gbm_vec(10000, mu = 0.2)
    option_sim_profit(gbm, type="put", X = 70) -> a
    option_sim_profit(gbm, type="call", X = 130) -> b
    profit_strangle <-(-a$profit-b$profit)*100*1.68
    plot(density(profit_straddle), xlim=c(-20000, 3000), lwd=2); lines(density(profit_strangle), col="blue", lwd=2)
    
}

# Simulate some examples from "The second leg down" - Hari Krishnan
{
    # Replicating call portfolio (probably wrong)
    gbm <- gbm_vec(1, sigma = 0.1) %>% as.vector
    tte <- seq(1, 1/365, length.out=365)
    values <-  bscall(gbm, 100, 0.2, 0, tte, 0)
    deltas <- greeks(bscall(gbm, 100, 0.2, 0, tte, 0), complete=FALSE, long=FALSE, initcaps=FALSE)["delta",]
    portfolio <- deltas * gbm - (deltas * 100 - values)
    matplot2(cbind(portfolio, values))
    # Figure 3.23
    SPY %>% filter(call_put=="Put") %>% mutate(delta_ = abs(round(delta, 1))) %>% filter(delta_ %in%  c(0.2, 0.5)) %>% group_by(date, expiration) %>% mutate(N=n()) %>% filter(N==2) %>% arrange(delta_, .by_group = TRUE) %>% group_by(date, expiration) %>% reframe(Vol=(first(vol)-last(vol))*100, Return=first(Return6month)*100) %>% ggplot(aes(Return, Vol)) + geom_point() + geom_smooth(method = "lm") + ylim(c(-15,15))
    # Figure 3.42
    SPY %>% filter(call_put=="Put") %>% filter(between(dte, 20,40)) %>% mutate(delta_ = abs(round(delta, 1))) %>% filter(delta_ %in%  c(0.2, 0.5)) %>% group_by(date, expiration) %>% mutate(N=n()) %>% filter(N==2) %>% arrange(delta_, .by_group = TRUE) %>% group_by(date, expiration) %>% reframe(Vol=(first(vol)-last(vol))*100) %>% ggplot(aes(date, Vol)) + geom_line() 
    # Figure 4.5
    SPY %>% filter(call_put=="Put")  %>% mutate(delta_ = abs(round_to_nearest(delta, 0.05))) %>% group_by(id) %>% mutate(Profit = log(mid / lag(mid))) %>% group_by(delta_)%>% filter(!is.infinite(Profit) & between(dte, 20, 40)) %>% reframe(M=-mean(Profit/HV1, na.rm=T)) %>% ggplot(aes(x=delta_,y=M)) + geom_bar(stat="identity")
}


# Plot greeks (as described in derivmkts)
{
    k <- 100; r <- 0; v <- 0.30; tt <- 1; d <- 0
    S <- seq(50, 150, by=1)
    Call <- greeks(bscall(S, k, v, r, tt, d), long = TRUE)
    Put <- greeks(bsput(S, k, v, r, tt, d), long = TRUE)
    ggplot(rbind(Call, Put), aes(x = s, y = value, color = funcname )) +
        geom_line() + facet_wrap(~ greek, scales = 'free_y') +
        scale_color_discrete(name = 'Option', labels = c('Call','Put' )) +
        scale_x_continuous('Stock', breaks =c(0, 100, 200) ) +
        scale_y_continuous('Value')
}

# Quantra backtesting
{
    df_strike <- DF
    df_strike$R <- round(df_strike$`[UNDERLYING_LAST]`/25)*25
    df_strike <- filter(df_strike, `[STRIKE]`==R)
    df_strike$Return <- log(df_strike$`[UNDERLYING_LAST]` / lag(df_strike$`[UNDERLYING_LAST]`))
    df_strike$RV <- runMean(df_strike$Return^2, 20) ; 
    df_strike$Signal <- -sign(mean(c(df_strike$`[C_IV]`, df_strike$`[P_IV]`)) - df_strike$RV)
    df_0 <- filter(DF, `[DTE]`==0)
    res <- list()
    for(i in 2:30) {
        df <- filter(df_strike, `[DTE]`==i)
        df_merge <- merge(df, df_0, by="[EXPIRE_DATE]") %>% 
            dplyr::select(`[EXPIRE_DATE]`, `[QUOTE_DATE].x`, `[QUOTE_DATE].y`, `[STRIKE].x`, `[STRIKE].y`, `[C_IV].x`, `[C_IV].y`, `[P_IV].x`, `[P_IV].y`,`[C_LAST].x`, `[C_LAST].y`, `[P_LAST].x`, `[P_LAST].y`, RV, Signal) %>% 
            filter(`[STRIKE].x` == `[STRIKE].y`) %>% mutate(PnL = -(`[C_LAST].y` - `[C_LAST].x`) + -(`[P_LAST].y` - `[P_LAST].x`))
        res[[as.character(i)]] <- data.frame(Date=df_merge$`[QUOTE_DATE].y`, PnL=df_merge$PnL) %>% arrange(Date)
    }
    full <- Reduce(function(...) full_join(..., by = "Date"), res) %>% arrange(Date) #%>% dplyr::select(-Date) %>% apply(., 2, function(x) replace(x, is.na(x), 0))
    colnames(full) <- as.character( 2:30)
    full[,-1] <- apply(full[,-1], 2, cumsum)
}
